apiVersion: v1
kind: Service

metadata:
  name: nginx-svc
  namespace: nginx-ns

spec:
  selector:
    app: nginx

  ports:
    - protocol: TCP
      port: 82              # cluster / host port
      targetPort : 80       # container port

